import { z } from "zod";
import {
  AccountsPayableInvoiceSchema,
  AccountsPayableOverviewSchema,
  AccountsPayableRiskSchema,
  AuditEventSchema,
  AuthSessionSchema,
  AuthSessionActivitiesSchema,
  AuthSessionActivitySchema,
  BudgetBookLineSchema,
  BudgetBookOverviewSchema,
  BudgetBookRiskSchema,
  CashFlowLineSchema,
  CashFlowOverviewSchema,
  CashFlowRiskSchema,
  CloseControlLineSchema,
  CloseControlOverviewSchema,
  CloseControlRiskSchema,
  SupplierControlLineSchema,
  SupplierControlOverviewSchema,
  SupplierControlRiskSchema,
  SupplierMasterOverviewSchema,
  SupplierMasterProfileSchema,
  SupplierMasterRiskSchema,
  ComplianceCaseSchema,
  ComplianceOverviewSchema,
  ComplianceRiskSchema,
  CostControlExceptionSchema,
  CostControlLineSchema,
  CostControlOverviewSchema,
  CrmLeadBucketSchema,
  CrmOverviewSchema,
  CrmRiskSchema,
  DailyLogEntrySchema,
  DailyLogOverviewSchema,
  DailyLogRiskSchema,
  DocumentControlItemSchema,
  DocumentControlOverviewSchema,
  DocumentControlRiskSchema,
  EquipmentOverviewSchema,
  EstimationCollectionExceptionSchema,
  EstimationCollectionLineSchema,
  EstimationCollectionOverviewSchema,
  CompanyDetailSchema,
  CompanySchema,
  CompanyModuleStateSchema,
  CreateAccountsPayableInvoiceRequestSchema,
  CreateTreasuryPaymentRunRequestSchema,
  CreateProjectPortfolioItemRequestSchema,
  CreateDailyLogEntryRequestSchema,
  CreateDocumentControlItemRequestSchema,
  CreateFieldMaterialRequestRequestSchema,
  CreateFieldMaterialRequestResponseSchema,
  CreateInventoryMovementRequestSchema,
  CreateInventoryReceiptRequestSchema,
  CreateMachineItemRequestSchema,
  CreateQualityInspectionRequestSchema,
  CreateProcurementPurchaseOrderRequestSchema,
  CreateProcurementRequisitionRequestSchema,
  CreateSupplierControlLineRequestSchema,
  CreateSupplierMasterProfileRequestSchema,
  FinanceLedgerItemSchema,
  FinanceOverviewSchema,
  FinanceRiskSchema,
  FieldMaterialRequestSchema,
  FieldMaterialRequestOverviewSchema,
  HrOverviewSchema,
  HrRiskSchema,
  HrWorkforceItemSchema,
  IntegrationOverviewSchema,
  IntegrationRiskSchema,
  IntegrationStreamSchema,
  InventoryLocationSchema,
  InventoryOverviewSchema,
  InventoryRiskSchema,
  InventoryReceiptSchema,
  InventoryReceivingOverviewSchema,
  InventoryReceiptRiskSchema,
  InventoryMovementSchema,
  InventoryMovementsOverviewSchema,
  InventoryMovementRiskSchema,
  MachineItemSchema,
  MachineRiskSchema,
  ModuleSchema,
  PostSaleCaseSchema,
  PostSaleOverviewSchema,
  PostSaleRiskSchema,
  PlatformBootstrapSchema,
  PlatformDashboardSummarySchema,
  PlatformReadinessCheckSchema,
  PlatformSettingsSchema,
  PlatformSystemReadinessSchema,
  ProcurementOverviewSchema,
  ProcurementPackageSchema,
  ProcurementPurchaseOrderRiskSchema,
  ProcurementPurchaseOrderSchema,
  ProcurementPurchaseOrdersOverviewSchema,
  ProcurementRequisitionSchema,
  ProcurementRequisitionsOverviewSchema,
  ProcurementRequisitionRiskSchema,
  ProcurementRiskSchema,
  UpdateAccountsPayableInvoiceRequestSchema,
  UpdateTreasuryPaymentRunRequestSchema,
  UpdateBudgetBookLineRequestSchema,
  UpdateCashFlowLineRequestSchema,
  UpdateCloseControlLineRequestSchema,
  UpdateSupplierControlLineRequestSchema,
  UpdateSupplierMasterProfileRequestSchema,
  UpdatePostSaleCaseRequestSchema,
  CreateProjectScheduleActivityRequestSchema,
  ImportProjectScheduleActivitySchema,
  ImportProjectScheduleActivitiesRequestSchema,
  ImportProjectScheduleActivitiesResponseSchema,
  ProjectPortfolioItemSchema,
  ProjectPortfolioOverviewSchema,
  ProjectRiskSchema,
  ProjectScheduleActivitySchema,
  ProjectScheduleOverviewSchema,
  QualityInspectionSchema,
  QualityOverviewSchema,
  QualityRiskSchema,
  ProvisionCompanyRequestSchema,
  ProvisionCompanyResponseSchema,
  RoleSchema,
  SubcontractLineSchema,
  SubcontractOverviewSchema,
  SubcontractRiskSchema,
  UpdateEstimationCollectionLineRequestSchema,
  UpdateCostControlLineRequestSchema,
  UpdateComplianceCaseRequestSchema,
  UpdateCrmLeadBucketRequestSchema,
  UpdateDailyLogEntryRequestSchema,
  UpdateDocumentControlItemRequestSchema,
  UpdateFinanceLedgerItemRequestSchema,
  UpdateHrWorkforceItemRequestSchema,
  UpdateIntegrationStreamRequestSchema,
  UpdateInventoryLocationRequestSchema,
  UpdateInventoryReceiptRequestSchema,
  UpdateInventoryMovementRequestSchema,
  UpdateMachineItemRequestSchema,
  UpdateProjectPortfolioItemRequestSchema,
  UpdateProjectScheduleActivityRequestSchema,
  UpdateProcurementPackageRequestSchema,
  UpdateProcurementPurchaseOrderRequestSchema,
  UpdateProcurementRequisitionRequestSchema,
  UpdateQualityInspectionRequestSchema,
  UpdateCompanyModulesRequestSchema,
  UpdatePlatformSettingsRequestSchema,
  UserSchema,
  TreasuryPaymentRunInvoiceSchema,
  TreasuryPaymentRunRiskSchema,
  TreasuryPaymentRunSchema,
  TreasuryPaymentRunsOverviewSchema,
  defaultRoles,
  moduleAreas,
  moduleCatalog,
  moduleScopes,
  userStatuses
} from "@arcont/contracts";

export {
  AccountsPayableInvoiceSchema,
  AccountsPayableOverviewSchema,
  AccountsPayableRiskSchema,
  AuditEventSchema,
  AuthSessionSchema,
  AuthSessionActivitiesSchema,
  AuthSessionActivitySchema,
  BudgetBookLineSchema,
  BudgetBookOverviewSchema,
  BudgetBookRiskSchema,
  CashFlowLineSchema,
  CashFlowOverviewSchema,
  CashFlowRiskSchema,
  CloseControlLineSchema,
  CloseControlOverviewSchema,
  CloseControlRiskSchema,
  SupplierControlLineSchema,
  SupplierControlOverviewSchema,
  SupplierControlRiskSchema,
  SupplierMasterOverviewSchema,
  SupplierMasterProfileSchema,
  SupplierMasterRiskSchema,
  ComplianceCaseSchema,
  ComplianceOverviewSchema,
  ComplianceRiskSchema,
  CostControlExceptionSchema,
  CostControlLineSchema,
  CostControlOverviewSchema,
  CrmLeadBucketSchema,
  CrmOverviewSchema,
  CrmRiskSchema,
  DailyLogEntrySchema,
  DailyLogOverviewSchema,
  DailyLogRiskSchema,
  DocumentControlItemSchema,
  DocumentControlOverviewSchema,
  DocumentControlRiskSchema,
  EquipmentOverviewSchema,
  EstimationCollectionExceptionSchema,
  EstimationCollectionLineSchema,
  EstimationCollectionOverviewSchema,
  CompanyDetailSchema,
  CompanySchema,
  CompanyModuleStateSchema,
  CreateAccountsPayableInvoiceRequestSchema,
  CreateTreasuryPaymentRunRequestSchema,
  CreateProjectPortfolioItemRequestSchema,
  CreateDailyLogEntryRequestSchema,
  CreateDocumentControlItemRequestSchema,
  CreateFieldMaterialRequestRequestSchema,
  CreateFieldMaterialRequestResponseSchema,
  CreateInventoryMovementRequestSchema,
  CreateInventoryReceiptRequestSchema,
  CreateMachineItemRequestSchema,
  CreateQualityInspectionRequestSchema,
  CreateProcurementPurchaseOrderRequestSchema,
  CreateProcurementRequisitionRequestSchema,
  CreateSupplierControlLineRequestSchema,
  CreateSupplierMasterProfileRequestSchema,
  FinanceLedgerItemSchema,
  FinanceOverviewSchema,
  FinanceRiskSchema,
  FieldMaterialRequestSchema,
  FieldMaterialRequestOverviewSchema,
  HrOverviewSchema,
  HrRiskSchema,
  HrWorkforceItemSchema,
  IntegrationOverviewSchema,
  IntegrationRiskSchema,
  IntegrationStreamSchema,
  InventoryLocationSchema,
  InventoryOverviewSchema,
  InventoryRiskSchema,
  InventoryReceiptSchema,
  InventoryReceivingOverviewSchema,
  InventoryReceiptRiskSchema,
  InventoryMovementSchema,
  InventoryMovementsOverviewSchema,
  InventoryMovementRiskSchema,
  MachineItemSchema,
  MachineRiskSchema,
  ModuleSchema,
  PostSaleCaseSchema,
  PostSaleOverviewSchema,
  PostSaleRiskSchema,
  PlatformSettingsSchema,
  ProcurementOverviewSchema,
  ProcurementPackageSchema,
  ProcurementPurchaseOrderRiskSchema,
  ProcurementPurchaseOrderSchema,
  ProcurementPurchaseOrdersOverviewSchema,
  ProcurementRequisitionSchema,
  ProcurementRequisitionsOverviewSchema,
  ProcurementRequisitionRiskSchema,
  ProcurementRiskSchema,
  UpdateAccountsPayableInvoiceRequestSchema,
  UpdateTreasuryPaymentRunRequestSchema,
  UpdateBudgetBookLineRequestSchema,
  UpdateCashFlowLineRequestSchema,
  UpdateCloseControlLineRequestSchema,
  UpdateSupplierControlLineRequestSchema,
  UpdateSupplierMasterProfileRequestSchema,
  UpdatePostSaleCaseRequestSchema,
  CreateProjectScheduleActivityRequestSchema,
  ImportProjectScheduleActivitySchema,
  ImportProjectScheduleActivitiesRequestSchema,
  ImportProjectScheduleActivitiesResponseSchema,
  ProjectPortfolioItemSchema,
  ProjectPortfolioOverviewSchema,
  ProjectRiskSchema,
  ProjectScheduleActivitySchema,
  ProjectScheduleOverviewSchema,
  QualityInspectionSchema,
  QualityOverviewSchema,
  QualityRiskSchema,
  PlatformBootstrapSchema,
  PlatformDashboardSummarySchema,
  ProvisionCompanyRequestSchema,
  ProvisionCompanyResponseSchema,
  RoleSchema,
  SubcontractLineSchema,
  SubcontractOverviewSchema,
  SubcontractRiskSchema,
  UpdateEstimationCollectionLineRequestSchema,
  UpdateCostControlLineRequestSchema,
  UpdateComplianceCaseRequestSchema,
  UpdateCrmLeadBucketRequestSchema,
  UpdateDailyLogEntryRequestSchema,
  UpdateDocumentControlItemRequestSchema,
  UpdateFinanceLedgerItemRequestSchema,
  UpdateHrWorkforceItemRequestSchema,
  UpdateIntegrationStreamRequestSchema,
  UpdateInventoryLocationRequestSchema,
  UpdateInventoryReceiptRequestSchema,
  UpdateInventoryMovementRequestSchema,
  UpdateMachineItemRequestSchema,
  UpdateProjectPortfolioItemRequestSchema,
  UpdateProjectScheduleActivityRequestSchema,
  UpdateProcurementPackageRequestSchema,
  UpdateProcurementPurchaseOrderRequestSchema,
  UpdateProcurementRequisitionRequestSchema,
  UpdateQualityInspectionRequestSchema,
  UpdateCompanyModulesRequestSchema,
  UpdatePlatformSettingsRequestSchema,
  UserSchema,
  TreasuryPaymentRunInvoiceSchema,
  TreasuryPaymentRunRiskSchema,
  TreasuryPaymentRunSchema,
  TreasuryPaymentRunsOverviewSchema,
  defaultRoles,
  moduleAreas,
  moduleCatalog,
  moduleScopes,
  userStatuses
};

export const CreatePlatformUserRequestSchema = z.object({
  companyId: z.string(),
  fullName: z.string().min(3),
  email: z.string().email(),
  roleKey: z.string(),
  status: z.enum(userStatuses).default("invited")
});

export const UpdatePlatformUserRoleRequestSchema = z.object({
  roleKey: z.string()
});

export const UpdatePlatformUserStatusRequestSchema = z.object({
  status: z.enum(userStatuses)
});

export const CreateSubcontractLineRequestSchema = z.object({
  code: z.string().min(3),
  contractorName: z.string().min(3),
  projectName: z.string().min(3),
  frontName: z.string().min(3),
  activeHeadcount: z.number().int().positive(),
  attendanceRate: z.number().min(0).max(100),
  productivityRate: z.number().min(0).max(100),
  complianceExpirations: z.number().int().nonnegative(),
  incidentCount: z.number().int().nonnegative(),
  subcontractHealth: z.enum(["controlled", "watch", "critical"]),
  nextAction: z.string().min(8)
});

export const UpdateSubcontractLineRequestSchema = z.object({
  subcontractHealth: z.enum(["controlled", "watch", "critical"]),
  nextAction: z.string().min(8)
});

export const PlatformUserDetailSchema = z.object({
  user: UserSchema,
  company: CompanySchema,
  role: RoleSchema,
  permissions: z.array(z.string())
});

export const CreatePlatformUserResponseSchema = z.object({
  user: UserSchema,
  temporaryPassword: z.string(),
  role: RoleSchema,
  permissions: z.array(z.string())
});

export const PlatformApiErrorSchema = z.object({
  error: z.object({
    code: z.string(),
    message: z.string(),
    details: z.record(z.string(), z.unknown()).optional()
  })
});

export type {
  AccountsPayableInvoiceContract,
  AccountsPayableOverviewContract,
  AccountsPayableRiskContract,
  AuditEventContract,
  AuthLoginRequestContract,
  AuthSessionContract,
  AuthSessionActivitiesContract,
  AuthSessionActivityContract,
  BudgetBookLineContract,
  BudgetBookOverviewContract,
  BudgetBookRiskContract,
  CashFlowLineContract,
  CashFlowOverviewContract,
  CashFlowRiskContract,
  CloseControlLineContract,
  CloseControlOverviewContract,
  CloseControlRiskContract,
  SupplierControlLineContract,
  SupplierControlOverviewContract,
  SupplierControlRiskContract,
  SupplierMasterOverviewContract,
  SupplierMasterProfileContract,
  SupplierMasterRiskContract,
  ComplianceCaseContract,
  ComplianceOverviewContract,
  ComplianceRiskContract,
  CostControlExceptionContract,
  CostControlLineContract,
  CostControlOverviewContract,
  CrmLeadBucketContract,
  CrmOverviewContract,
  CrmRiskContract,
  DailyLogEntryContract,
  DailyLogOverviewContract,
  DailyLogRiskContract,
  DocumentControlItemContract,
  DocumentControlOverviewContract,
  DocumentControlRiskContract,
  EquipmentOverviewContract,
  EstimationCollectionExceptionContract,
  EstimationCollectionLineContract,
  EstimationCollectionOverviewContract,
  CompanyDetailContract,
  CompanyContract,
  CompanyModuleStateContract,
  CreateAccountsPayableInvoiceRequestContract,
  CreateTreasuryPaymentRunRequestContract,
  CreateProjectPortfolioItemRequestContract,
  CreateProjectScheduleActivityRequestContract,
  ImportProjectScheduleActivityContract,
  ImportProjectScheduleActivitiesRequestContract,
  ImportProjectScheduleActivitiesResponseContract,
  CreateDailyLogEntryRequestContract,
  CreateDocumentControlItemRequestContract,
  CreateFieldMaterialRequestRequestContract,
  CreateFieldMaterialRequestResponseContract,
  CreateInventoryMovementRequestContract,
  CreateInventoryReceiptRequestContract,
  CreateMachineItemRequestContract,
  CreateQualityInspectionRequestContract,
  CreateProcurementPurchaseOrderRequestContract,
  CreateProcurementRequisitionRequestContract,
  CreateSupplierControlLineRequestContract,
  CreateSupplierMasterProfileRequestContract,
  FinanceLedgerItemContract,
  FinanceOverviewContract,
  FinanceRiskContract,
  FieldMaterialRequestContract,
  FieldMaterialRequestOverviewContract,
  HrOverviewContract,
  HrRiskContract,
  HrWorkforceItemContract,
  IntegrationOverviewContract,
  IntegrationRiskContract,
  IntegrationStreamContract,
  InventoryLocationContract,
  InventoryOverviewContract,
  InventoryRiskContract,
  InventoryReceiptContract,
  InventoryReceivingOverviewContract,
  InventoryReceiptRiskContract,
  InventoryMovementContract,
  InventoryMovementsOverviewContract,
  InventoryMovementRiskContract,
  MachineItemContract,
  MachineRiskContract,
  ModuleContract,
  PostSaleCaseContract,
  PostSaleOverviewContract,
  PostSaleRiskContract,
  PlatformBootstrapContract,
  PlatformDashboardSummaryContract,
  PlatformSettingsContract,
  ProcurementOverviewContract,
  ProcurementPackageContract,
  ProcurementPurchaseOrderContract,
  ProcurementPurchaseOrderRiskContract,
  ProcurementPurchaseOrdersOverviewContract,
  ProcurementRequisitionContract,
  ProcurementRequisitionsOverviewContract,
  ProcurementRequisitionRiskContract,
  ProcurementRiskContract,
  UpdateAccountsPayableInvoiceRequestContract,
  UpdateTreasuryPaymentRunRequestContract,
  TreasuryPaymentRunInvoiceContract,
  TreasuryPaymentRunRiskContract,
  TreasuryPaymentRunContract,
  TreasuryPaymentRunsOverviewContract,
  UpdateBudgetBookLineRequestContract,
  UpdateCashFlowLineRequestContract,
  UpdateCloseControlLineRequestContract,
  UpdateSupplierControlLineRequestContract,
  UpdateSupplierMasterProfileRequestContract,
  UpdatePostSaleCaseRequestContract,
  ProjectPortfolioItemContract,
  ProjectPortfolioOverviewContract,
  ProjectRiskContract,
  ProjectScheduleActivityContract,
  ProjectScheduleOverviewContract,
  QualityInspectionContract,
  QualityOverviewContract,
  QualityRiskContract,
  ProvisionCompanyRequestContract,
  ProvisionCompanyResponseContract,
  RoleContract,
  SubcontractLineContract,
  SubcontractOverviewContract,
  SubcontractRiskContract,
  UpdateEstimationCollectionLineRequestContract,
  UpdateCostControlLineRequestContract,
  UpdateComplianceCaseRequestContract,
  UpdateCrmLeadBucketRequestContract,
  UpdateDailyLogEntryRequestContract,
  UpdateDocumentControlItemRequestContract,
  UpdateFinanceLedgerItemRequestContract,
  UpdateHrWorkforceItemRequestContract,
  UpdateIntegrationStreamRequestContract,
  UpdateInventoryLocationRequestContract,
  UpdateInventoryReceiptRequestContract,
  UpdateInventoryMovementRequestContract,
  UpdateMachineItemRequestContract,
  UpdateProjectPortfolioItemRequestContract,
  UpdateProjectScheduleActivityRequestContract,
  UpdateProcurementPackageRequestContract,
  UpdateProcurementPurchaseOrderRequestContract,
  UpdateProcurementRequisitionRequestContract,
  UpdateQualityInspectionRequestContract,
  UpdateCompanyModulesRequestContract,
  UpdatePlatformSettingsRequestContract,
  UserContract
} from "@arcont/contracts";

export type CreatePlatformUserRequestContract = z.infer<typeof CreatePlatformUserRequestSchema>;
export type UpdatePlatformUserRoleRequestContract = z.infer<typeof UpdatePlatformUserRoleRequestSchema>;
export type UpdatePlatformUserStatusRequestContract = z.infer<typeof UpdatePlatformUserStatusRequestSchema>;
export type PlatformUserDetailContract = z.infer<typeof PlatformUserDetailSchema>;
export type CreatePlatformUserResponseContract = z.infer<typeof CreatePlatformUserResponseSchema>;
export type PlatformApiErrorContract = z.infer<typeof PlatformApiErrorSchema>;
export type CreateSubcontractLineRequestContract = z.infer<typeof CreateSubcontractLineRequestSchema>;
export type UpdateSubcontractLineRequestContract = z.infer<typeof UpdateSubcontractLineRequestSchema>;
export type PlatformReadinessCheckContract = z.infer<typeof PlatformReadinessCheckSchema>;
export type PlatformSystemReadinessContract = z.infer<typeof PlatformSystemReadinessSchema>;
export { PlatformReadinessCheckSchema, PlatformSystemReadinessSchema };
