import { z } from "zod";
import {
  AuditEventSchema,
  AuthSessionSchema,
  AuthSessionActivitiesSchema,
  AuthSessionActivitySchema,
  BudgetBookLineSchema,
  BudgetBookOverviewSchema,
  BudgetBookRiskSchema,
  CashFlowLineSchema,
  CashFlowOverviewSchema,
  CashFlowRiskSchema,
  CloseControlLineSchema,
  CloseControlOverviewSchema,
  CloseControlRiskSchema,
  SupplierControlLineSchema,
  SupplierControlOverviewSchema,
  SupplierControlRiskSchema,
  ComplianceCaseSchema,
  ComplianceOverviewSchema,
  ComplianceRiskSchema,
  CostControlExceptionSchema,
  CostControlLineSchema,
  CostControlOverviewSchema,
  CrmLeadBucketSchema,
  CrmOverviewSchema,
  CrmRiskSchema,
  DailyLogEntrySchema,
  DailyLogOverviewSchema,
  DailyLogRiskSchema,
  DocumentControlItemSchema,
  DocumentControlOverviewSchema,
  DocumentControlRiskSchema,
  EquipmentOverviewSchema,
  EstimationCollectionExceptionSchema,
  EstimationCollectionLineSchema,
  EstimationCollectionOverviewSchema,
  CompanyDetailSchema,
  CompanySchema,
  CompanyModuleStateSchema,
  FinanceLedgerItemSchema,
  FinanceOverviewSchema,
  FinanceRiskSchema,
  HrOverviewSchema,
  HrRiskSchema,
  HrWorkforceItemSchema,
  IntegrationOverviewSchema,
  IntegrationRiskSchema,
  IntegrationStreamSchema,
  InventoryLocationSchema,
  InventoryOverviewSchema,
  InventoryRiskSchema,
  InventoryReceiptSchema,
  InventoryReceivingOverviewSchema,
  InventoryReceiptRiskSchema,
  InventoryMovementSchema,
  InventoryMovementsOverviewSchema,
  InventoryMovementRiskSchema,
  MachineItemSchema,
  MachineRiskSchema,
  ModuleSchema,
  PostSaleCaseSchema,
  PostSaleOverviewSchema,
  PostSaleRiskSchema,
  PlatformBootstrapSchema,
  PlatformDashboardSummarySchema,
  PlatformSettingsSchema,
  ProcurementOverviewSchema,
  ProcurementPackageSchema,
  ProcurementRiskSchema,
  UpdateBudgetBookLineRequestSchema,
  UpdateCashFlowLineRequestSchema,
  UpdateCloseControlLineRequestSchema,
  UpdateSupplierControlLineRequestSchema,
  UpdatePostSaleCaseRequestSchema,
  ProjectPortfolioItemSchema,
  ProjectPortfolioOverviewSchema,
  ProjectRiskSchema,
  QualityInspectionSchema,
  QualityOverviewSchema,
  QualityRiskSchema,
  ProvisionCompanyRequestSchema,
  ProvisionCompanyResponseSchema,
  RoleSchema,
  SubcontractLineSchema,
  SubcontractOverviewSchema,
  SubcontractRiskSchema,
  UpdateEstimationCollectionLineRequestSchema,
  UpdateCostControlLineRequestSchema,
  UpdateComplianceCaseRequestSchema,
  UpdateCrmLeadBucketRequestSchema,
  UpdateDailyLogEntryRequestSchema,
  UpdateDocumentControlItemRequestSchema,
  UpdateFinanceLedgerItemRequestSchema,
  UpdateHrWorkforceItemRequestSchema,
  UpdateIntegrationStreamRequestSchema,
  UpdateInventoryLocationRequestSchema,
  UpdateInventoryReceiptRequestSchema,
  UpdateInventoryMovementRequestSchema,
  UpdateMachineItemRequestSchema,
  UpdateProjectPortfolioItemRequestSchema,
  UpdateProcurementPackageRequestSchema,
  UpdateQualityInspectionRequestSchema,
  UpdateCompanyModulesRequestSchema,
  UpdatePlatformSettingsRequestSchema,
  UserSchema,
  defaultRoles,
  moduleAreas,
  moduleCatalog,
  moduleScopes,
  userStatuses
} from "@arcont/contracts";

export {
  AuditEventSchema,
  AuthSessionSchema,
  AuthSessionActivitiesSchema,
  AuthSessionActivitySchema,
  BudgetBookLineSchema,
  BudgetBookOverviewSchema,
  BudgetBookRiskSchema,
  CashFlowLineSchema,
  CashFlowOverviewSchema,
  CashFlowRiskSchema,
  CloseControlLineSchema,
  CloseControlOverviewSchema,
  CloseControlRiskSchema,
  SupplierControlLineSchema,
  SupplierControlOverviewSchema,
  SupplierControlRiskSchema,
  ComplianceCaseSchema,
  ComplianceOverviewSchema,
  ComplianceRiskSchema,
  CostControlExceptionSchema,
  CostControlLineSchema,
  CostControlOverviewSchema,
  CrmLeadBucketSchema,
  CrmOverviewSchema,
  CrmRiskSchema,
  DailyLogEntrySchema,
  DailyLogOverviewSchema,
  DailyLogRiskSchema,
  DocumentControlItemSchema,
  DocumentControlOverviewSchema,
  DocumentControlRiskSchema,
  EquipmentOverviewSchema,
  EstimationCollectionExceptionSchema,
  EstimationCollectionLineSchema,
  EstimationCollectionOverviewSchema,
  CompanyDetailSchema,
  CompanySchema,
  CompanyModuleStateSchema,
  FinanceLedgerItemSchema,
  FinanceOverviewSchema,
  FinanceRiskSchema,
  HrOverviewSchema,
  HrRiskSchema,
  HrWorkforceItemSchema,
  IntegrationOverviewSchema,
  IntegrationRiskSchema,
  IntegrationStreamSchema,
  InventoryLocationSchema,
  InventoryOverviewSchema,
  InventoryRiskSchema,
  InventoryReceiptSchema,
  InventoryReceivingOverviewSchema,
  InventoryReceiptRiskSchema,
  InventoryMovementSchema,
  InventoryMovementsOverviewSchema,
  InventoryMovementRiskSchema,
  MachineItemSchema,
  MachineRiskSchema,
  ModuleSchema,
  PostSaleCaseSchema,
  PostSaleOverviewSchema,
  PostSaleRiskSchema,
  PlatformSettingsSchema,
  ProcurementOverviewSchema,
  ProcurementPackageSchema,
  ProcurementRiskSchema,
  UpdateBudgetBookLineRequestSchema,
  UpdateCashFlowLineRequestSchema,
  UpdateCloseControlLineRequestSchema,
  UpdateSupplierControlLineRequestSchema,
  UpdatePostSaleCaseRequestSchema,
  ProjectPortfolioItemSchema,
  ProjectPortfolioOverviewSchema,
  ProjectRiskSchema,
  QualityInspectionSchema,
  QualityOverviewSchema,
  QualityRiskSchema,
  PlatformBootstrapSchema,
  PlatformDashboardSummarySchema,
  ProvisionCompanyRequestSchema,
  ProvisionCompanyResponseSchema,
  RoleSchema,
  SubcontractLineSchema,
  SubcontractOverviewSchema,
  SubcontractRiskSchema,
  UpdateEstimationCollectionLineRequestSchema,
  UpdateCostControlLineRequestSchema,
  UpdateComplianceCaseRequestSchema,
  UpdateCrmLeadBucketRequestSchema,
  UpdateDailyLogEntryRequestSchema,
  UpdateDocumentControlItemRequestSchema,
  UpdateFinanceLedgerItemRequestSchema,
  UpdateHrWorkforceItemRequestSchema,
  UpdateIntegrationStreamRequestSchema,
  UpdateInventoryLocationRequestSchema,
  UpdateInventoryReceiptRequestSchema,
  UpdateInventoryMovementRequestSchema,
  UpdateMachineItemRequestSchema,
  UpdateProjectPortfolioItemRequestSchema,
  UpdateProcurementPackageRequestSchema,
  UpdateQualityInspectionRequestSchema,
  UpdateCompanyModulesRequestSchema,
  UpdatePlatformSettingsRequestSchema,
  UserSchema,
  defaultRoles,
  moduleAreas,
  moduleCatalog,
  moduleScopes,
  userStatuses
};

export const CreatePlatformUserRequestSchema = z.object({
  companyId: z.string(),
  fullName: z.string().min(3),
  email: z.string().email(),
  roleKey: z.string(),
  status: z.enum(userStatuses).default("invited")
});

export const UpdatePlatformUserRoleRequestSchema = z.object({
  roleKey: z.string()
});

export const UpdatePlatformUserStatusRequestSchema = z.object({
  status: z.enum(userStatuses)
});

export const UpdateSubcontractLineRequestSchema = z.object({
  subcontractHealth: z.enum(["controlled", "watch", "critical"]),
  nextAction: z.string().min(8)
});

export const PlatformUserDetailSchema = z.object({
  user: UserSchema,
  company: CompanySchema,
  role: RoleSchema,
  permissions: z.array(z.string())
});

export const CreatePlatformUserResponseSchema = z.object({
  user: UserSchema,
  temporaryPassword: z.string(),
  role: RoleSchema,
  permissions: z.array(z.string())
});

export const PlatformApiErrorSchema = z.object({
  error: z.object({
    code: z.string(),
    message: z.string(),
    details: z.record(z.string(), z.unknown()).optional()
  })
});

export type {
  AuditEventContract,
  AuthLoginRequestContract,
  AuthSessionContract,
  AuthSessionActivitiesContract,
  AuthSessionActivityContract,
  BudgetBookLineContract,
  BudgetBookOverviewContract,
  BudgetBookRiskContract,
  CashFlowLineContract,
  CashFlowOverviewContract,
  CashFlowRiskContract,
  CloseControlLineContract,
  CloseControlOverviewContract,
  CloseControlRiskContract,
  SupplierControlLineContract,
  SupplierControlOverviewContract,
  SupplierControlRiskContract,
  ComplianceCaseContract,
  ComplianceOverviewContract,
  ComplianceRiskContract,
  CostControlExceptionContract,
  CostControlLineContract,
  CostControlOverviewContract,
  CrmLeadBucketContract,
  CrmOverviewContract,
  CrmRiskContract,
  DailyLogEntryContract,
  DailyLogOverviewContract,
  DailyLogRiskContract,
  DocumentControlItemContract,
  DocumentControlOverviewContract,
  DocumentControlRiskContract,
  EquipmentOverviewContract,
  EstimationCollectionExceptionContract,
  EstimationCollectionLineContract,
  EstimationCollectionOverviewContract,
  CompanyDetailContract,
  CompanyContract,
  CompanyModuleStateContract,
  FinanceLedgerItemContract,
  FinanceOverviewContract,
  FinanceRiskContract,
  HrOverviewContract,
  HrRiskContract,
  HrWorkforceItemContract,
  IntegrationOverviewContract,
  IntegrationRiskContract,
  IntegrationStreamContract,
  InventoryLocationContract,
  InventoryOverviewContract,
  InventoryRiskContract,
  InventoryReceiptContract,
  InventoryReceivingOverviewContract,
  InventoryReceiptRiskContract,
  InventoryMovementContract,
  InventoryMovementsOverviewContract,
  InventoryMovementRiskContract,
  MachineItemContract,
  MachineRiskContract,
  ModuleContract,
  PostSaleCaseContract,
  PostSaleOverviewContract,
  PostSaleRiskContract,
  PlatformBootstrapContract,
  PlatformDashboardSummaryContract,
  PlatformSettingsContract,
  ProcurementOverviewContract,
  ProcurementPackageContract,
  ProcurementRiskContract,
  UpdateBudgetBookLineRequestContract,
  UpdateCashFlowLineRequestContract,
  UpdateCloseControlLineRequestContract,
  UpdateSupplierControlLineRequestContract,
  UpdatePostSaleCaseRequestContract,
  ProjectPortfolioItemContract,
  ProjectPortfolioOverviewContract,
  ProjectRiskContract,
  QualityInspectionContract,
  QualityOverviewContract,
  QualityRiskContract,
  ProvisionCompanyRequestContract,
  ProvisionCompanyResponseContract,
  RoleContract,
  SubcontractLineContract,
  SubcontractOverviewContract,
  SubcontractRiskContract,
  UpdateEstimationCollectionLineRequestContract,
  UpdateCostControlLineRequestContract,
  UpdateComplianceCaseRequestContract,
  UpdateCrmLeadBucketRequestContract,
  UpdateDailyLogEntryRequestContract,
  UpdateDocumentControlItemRequestContract,
  UpdateFinanceLedgerItemRequestContract,
  UpdateHrWorkforceItemRequestContract,
  UpdateIntegrationStreamRequestContract,
  UpdateInventoryLocationRequestContract,
  UpdateInventoryReceiptRequestContract,
  UpdateInventoryMovementRequestContract,
  UpdateMachineItemRequestContract,
  UpdateProjectPortfolioItemRequestContract,
  UpdateProcurementPackageRequestContract,
  UpdateQualityInspectionRequestContract,
  UpdateCompanyModulesRequestContract,
  UpdatePlatformSettingsRequestContract,
  UserContract
} from "@arcont/contracts";

export type CreatePlatformUserRequestContract = z.infer<typeof CreatePlatformUserRequestSchema>;
export type UpdatePlatformUserRoleRequestContract = z.infer<typeof UpdatePlatformUserRoleRequestSchema>;
export type UpdatePlatformUserStatusRequestContract = z.infer<typeof UpdatePlatformUserStatusRequestSchema>;
export type PlatformUserDetailContract = z.infer<typeof PlatformUserDetailSchema>;
export type CreatePlatformUserResponseContract = z.infer<typeof CreatePlatformUserResponseSchema>;
export type PlatformApiErrorContract = z.infer<typeof PlatformApiErrorSchema>;
export type UpdateSubcontractLineRequestContract = z.infer<typeof UpdateSubcontractLineRequestSchema>;
